version: "3.9"

services:
  posterbot:
    build: .
    container_name: posterbot
    restart: unless-stopped
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
